name: Docker Smoke Test CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install python deps
      run: |
        pip install requests argpass

    - name: Run Python script to d/l model
      run: |
        python ./docker/open_llama/hug_model.py -a SlyEcho -f open-llama-3b-q5_1.bin

    - name: Install SlyEcho_open_llama_3b_ggml_open-llama-3b-q5_1.bin
      run: |
        rm -f model.bin
        mv SlyEcho_open_llama_3b_ggml_open-llama-3b-q5_1.bin ./docker/open_llama/model.bin

    - name: Build Docker image
      run: |
        docker build ./docker/open_llama --tag open_llama_3b

    - name: Run Docker image
      run: |
        ./docker/open_llama/start.sh
