name: Docker Smoke Test CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install python deps
      run: |
        pip install requests argpass

    - name: Run Python script to d/l model
      run: |
        python ./docker/open_llama/hug_model.py -a SlyEcho -s open_llama_3b -f "q5_1"

    - name: Replace symlink with target file
      run: |
        symlink="model.bin"
        target=$(readlink -f "$symlink")  # find the target of the symlink
        rm "$symlink"  # remove the symlink
        mv "$target" "$symlink"  # replace the target file with the name of the symlink

    - name: Build Docker image
      run: |
        docker build ./docker/open_llama --file ./docker/open_llama/Dockerfile --tag open_llama_3b

    - name: Run Docker image
      run: |
        ./docker/open_llama/start.sh
